import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Breadcrumb from "../components/Breadcrumb"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>        
      <Breadcrumb
          homeElement={'Home'}
          activeClasses='text-red-500'
          container='flex py-5 bg-gradient-to-r from-amber-200 to-green-500' 
          listClasses='hover:underline font-bold text-green-500'
          capitalizeLinks
        />
        {children}
        </body>
    </html>
  );
}
