import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Breadcrumb from "../components/Breadcrumb"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <Breadcrumb
          homeElement={'Home'}
          separator={<span> | </span>}
          activeClasses='text-violet-600'
          containerClasses='flex py-5 bg-gradient-to-r from-purple-600 to-blue-600' 
          listClasses='hover:underline font-bold'
          capitalizeLinks
        />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
